// Hand-written emoji catalogue for pickers — no external dataset, no network.
// Keywords are English + French, so `searchEmoji` works in either interface
// language; supply your own `groups` to replace the set entirely.
export interface EmojiEntry {
	emoji: string;
	/** Search keywords, lower-case, both languages. */
	keys: string;
}
export interface EmojiGroup {
	id: string;
	/** Group glyph shown in the tab strip. */
	icon: string;
	/** Accessible name of the tab. Translate it by supplying your own `groups`. */
	label: string;
	entries: EmojiEntry[];
}

const e = (emoji: string, keys: string): EmojiEntry => ({ emoji, keys });

export const EMOJI_GROUPS: readonly EmojiGroup[] = [
	{
		id: 'smileys',
		label: 'Smileys',
		icon: '😀',
		entries: [
			e('😀', 'grin smile sourire content happy'),
			e('😄', 'smile laugh rire joie'),
			e('😂', 'joy tears laugh rire larmes'),
			e('🙂', 'slight smile sourire'),
			e('😉', 'wink clin oeil'),
			e('😍', 'heart eyes love amour'),
			e('😎', 'cool sunglasses lunettes'),
			e('🤓', 'nerd glasses lunettes geek'),
			e('🧐', 'monocle inspect examiner'),
			e('🤔', 'think réfléchir penser'),
			e('🤖', 'robot bot machine'),
			e('👻', 'ghost fantôme'),
			e('💀', 'skull crâne tête de mort'),
			e('👽', 'alien extraterrestre'),
			e('🤡', 'clown'),
			e('😈', 'devil diable démon'),
			e('🥳', 'party fête célébration'),
			e('😴', 'sleep dormir zzz'),
			e('🤯', 'mind blown explosion tête'),
			e('🫠', 'melt fondre'),
			e('🙃', 'upside down envers'),
			e('😇', 'angel ange halo'),
			e('🤠', 'cowboy'),
			e('🥸', 'disguise déguisement moustache'),
			e('😶‍🌫️', 'fog brouillard nuage'),
		],
	},
	{
		id: 'people',
		label: 'People',
		icon: '🧑‍💻',
		entries: [
			e('🧑‍💻', 'technologist developer dev code ordinateur'),
			e('👩‍💻', 'woman technologist développeuse'),
			e('👨‍💻', 'man technologist développeur'),
			e('🧑‍🔬', 'scientist science labo'),
			e('🧑‍🚀', 'astronaut astronaute espace'),
			e('🧑‍🎨', 'artist artiste peinture'),
			e('🧑‍🍳', 'cook chef cuisine'),
			e('🧑‍🏫', 'teacher prof enseignant'),
			e('🧑‍⚕️', 'doctor médecin santé'),
			e('🧑‍🚒', 'firefighter pompier'),
			e('🕵️', 'detective détective enquête'),
			e('🧙', 'wizard mage magicien sorcier'),
			e('🧛', 'vampire'),
			e('🧟', 'zombie'),
			e('🦸', 'superhero héros super'),
			e('🦹', 'villain méchant'),
			e('🧞', 'genie génie'),
			e('👑', 'crown couronne roi reine king queen'),
			e('🎩', 'top hat chapeau haut de forme'),
			e('🧢', 'cap casquette'),
			e('👀', 'eyes yeux regarder'),
			e('🧠', 'brain cerveau'),
			e('💪', 'muscle biceps force'),
			e('👋', 'wave hello bonjour salut'),
			e('👍', 'thumbs up pouce ok'),
			e('🙏', 'pray please merci thanks'),
		],
	},
	{
		id: 'animals',
		label: 'Animals',
		icon: '🐙',
		entries: [
			e('🐙', 'octopus pieuvre poulpe'),
			e('🦀', 'crab crabe rust'),
			e('🐍', 'snake serpent python'),
			e('🐧', 'penguin pingouin manchot linux'),
			e('🐳', 'whale baleine docker'),
			e('🦊', 'fox renard'),
			e('🐺', 'wolf loup'),
			e('🦁', 'lion'),
			e('🐯', 'tiger tigre'),
			e('🐻', 'bear ours'),
			e('🐼', 'panda'),
			e('🐨', 'koala'),
			e('🐸', 'frog grenouille'),
			e('🦉', 'owl hibou chouette'),
			e('🦅', 'eagle aigle'),
			e('🦜', 'parrot perroquet'),
			e('🐝', 'bee abeille'),
			e('🦋', 'butterfly papillon'),
			e('🐢', 'turtle tortue'),
			e('🦈', 'shark requin'),
			e('🐬', 'dolphin dauphin'),
			e('🦄', 'unicorn licorne'),
			e('🐉', 'dragon'),
			e('🦖', 'dinosaur dinosaure t-rex'),
			e('🐱', 'cat chat'),
			e('🐶', 'dog chien'),
			e('🐭', 'mouse souris'),
			e('🐹', 'hamster'),
			e('🐰', 'rabbit lapin'),
			e('🦔', 'hedgehog hérisson'),
			e('🐘', 'elephant éléphant postgres'),
			e('🦒', 'giraffe girafe'),
			e('🐎', 'horse cheval'),
			e('🐐', 'goat chèvre'),
			e('🐔', 'chicken poule'),
			e('🦆', 'duck canard'),
			e('🐌', 'snail escargot lent'),
			e('🕷️', 'spider araignée'),
		],
	},
	{
		id: 'nature',
		label: 'Nature',
		icon: '🌿',
		entries: [
			e('🌿', 'herb plante feuille vert'),
			e('🍀', 'clover trèfle chance luck'),
			e('🌲', 'tree arbre sapin forêt'),
			e('🌵', 'cactus'),
			e('🌸', 'blossom fleur cerisier'),
			e('🌻', 'sunflower tournesol'),
			e('🌹', 'rose'),
			e('🍄', 'mushroom champignon'),
			e('🌍', 'earth terre monde globe'),
			e('🌙', 'moon lune nuit'),
			e('☀️', 'sun soleil jour'),
			e('⭐', 'star étoile'),
			e('🌟', 'glowing star étoile brillante'),
			e('✨', 'sparkles étincelles magie'),
			e('⚡', 'lightning éclair zap énergie'),
			e('🔥', 'fire feu flamme hot'),
			e('🌈', 'rainbow arc-en-ciel'),
			e('☁️', 'cloud nuage'),
			e('❄️', 'snowflake flocon neige froid'),
			e('🌊', 'wave vague mer océan'),
			e('🌋', 'volcano volcan'),
			e('🪐', 'planet planète saturne'),
			e('🚀', 'rocket fusée launch'),
			e('🛸', 'ufo soucoupe ovni'),
			e('☄️', 'comet comète'),
		],
	},
	{
		id: 'objects',
		label: 'Objects',
		icon: '🔧',
		entries: [
			e('🔧', 'wrench clé outil tool'),
			e('🔨', 'hammer marteau build'),
			e('🛠️', 'tools outils'),
			e('⚙️', 'gear engrenage réglages settings'),
			e('🔑', 'key clé password'),
			e('🔒', 'lock cadenas verrou sécurité'),
			e('🛡️', 'shield bouclier protection'),
			e('⚔️', 'swords épées'),
			e('🧰', 'toolbox boîte à outils'),
			e('🧪', 'test tube éprouvette labo'),
			e('🔬', 'microscope'),
			e('🔭', 'telescope télescope'),
			e('💻', 'laptop ordinateur portable'),
			e('🖥️', 'desktop écran ordinateur'),
			e('⌨️', 'keyboard clavier'),
			e('🖱️', 'mouse souris'),
			e('📱', 'phone téléphone mobile'),
			e('💾', 'floppy disquette save'),
			e('🗄️', 'cabinet classeur base données database'),
			e('📦', 'package paquet box colis'),
			e('📚', 'books livres docs'),
			e('📝', 'memo note écrire'),
			e('📌', 'pin punaise épingle'),
			e('🔖', 'bookmark marque-page'),
			e('💡', 'bulb idée ampoule'),
			e('🔦', 'flashlight lampe torche'),
			e('🧭', 'compass boussole'),
			e('⏰', 'alarm réveil horloge'),
			e('⏱️', 'stopwatch chrono'),
			e('🎯', 'target cible dart'),
			e('🎲', 'dice dé hasard'),
			e('🎮', 'game manette jeu'),
			e('🎸', 'guitar guitare musique'),
			e('🎵', 'music note musique'),
			e('🎧', 'headphones casque'),
			e('📷', 'camera appareil photo'),
			e('🎬', 'clapper cinéma film'),
			e('🧩', 'puzzle pièce'),
			e('🪄', 'magic wand baguette magique'),
			e('🧲', 'magnet aimant'),
			e('💎', 'gem diamant'),
			e('💰', 'money bag argent sac'),
			e('🪙', 'coin pièce'),
			e('🏆', 'trophy trophée coupe'),
			e('🥇', 'medal médaille or'),
			e('🎁', 'gift cadeau'),
			e('🎈', 'balloon ballon'),
			e('☕', 'coffee café'),
			e('🍕', 'pizza'),
			e('🍔', 'burger'),
			e('🍩', 'donut beignet'),
			e('🍪', 'cookie biscuit'),
			e('🍺', 'beer bière'),
			e('🍷', 'wine vin'),
			e('🚑', 'ambulance secours urgence rescue'),
			e('🚒', 'fire engine pompiers'),
			e('🚗', 'car voiture'),
			e('🚲', 'bike vélo'),
			e('✈️', 'plane avion'),
			e('🚂', 'train locomotive'),
			e('⛵', 'sailboat voilier bateau'),
			e('🏠', 'house maison home'),
			e('🏭', 'factory usine'),
			e('🏰', 'castle château'),
			e('🗼', 'tower tour'),
		],
	},
	{
		id: 'symbols',
		label: 'Symbols',
		icon: '❤️',
		entries: [
			e('❤️', 'heart coeur rouge love'),
			e('🧡', 'orange heart coeur'),
			e('💛', 'yellow heart coeur jaune'),
			e('💚', 'green heart coeur vert'),
			e('💙', 'blue heart coeur bleu'),
			e('💜', 'purple heart coeur violet'),
			e('🖤', 'black heart coeur noir'),
			e('🤍', 'white heart coeur blanc'),
			e('💯', 'hundred cent points'),
			e('✅', 'check coche ok validé'),
			e('❌', 'cross croix non erreur'),
			e('⚠️', 'warning attention'),
			e('🚫', 'forbidden interdit'),
			e('♻️', 'recycle recyclage'),
			e('🔴', 'red circle rond rouge'),
			e('🟠', 'orange circle rond'),
			e('🟡', 'yellow circle rond jaune'),
			e('🟢', 'green circle rond vert'),
			e('🔵', 'blue circle rond bleu'),
			e('🟣', 'purple circle rond violet'),
			e('⚫', 'black circle rond noir'),
			e('⚪', 'white circle rond blanc'),
			e('🟥', 'red square carré rouge'),
			e('🟧', 'orange square carré'),
			e('🟨', 'yellow square carré jaune'),
			e('🟩', 'green square carré vert'),
			e('🟦', 'blue square carré bleu'),
			e('🟪', 'purple square carré violet'),
			e('⬛', 'black square carré noir'),
			e('⬜', 'white square carré blanc'),
			e('🔶', 'orange diamond losange'),
			e('🔷', 'blue diamond losange bleu'),
			e('🔺', 'red triangle'),
			e('♠️', 'spade pique'),
			e('♣️', 'club trèfle'),
			e('♥️', 'heart coeur cartes'),
			e('♦️', 'diamond carreau'),
			e('☮️', 'peace paix'),
			e('☯️', 'yin yang'),
			e('♾️', 'infinity infini'),
			e('🔱', 'trident'),
			e('⚓', 'anchor ancre'),
			e('🏁', 'checkered flag drapeau arrivée'),
			e('🚩', 'red flag drapeau rouge'),
			e('🏴‍☠️', 'pirate flag drapeau pirate'),
			e('🇫🇷', 'france drapeau flag'),
			e('🇪🇺', 'europe eu drapeau flag'),
			e('🇺🇸', 'usa états-unis flag drapeau'),
			e('🇬🇧', 'uk royaume-uni flag drapeau'),
			e('🇩🇪', 'germany allemagne flag drapeau'),
			e('🇯🇵', 'japan japon flag drapeau'),
		],
	},
];

const fold = (s: string) => s.normalize('NFD').replace(/[̀-ͯ]/g, '').toLowerCase();

/** Entries matching a free-text query across every group; an empty query
 *  returns nothing (the caller shows the grouped grid instead). Accent-
 *  insensitive so « éléphant » and « elephant » both find the elephant. */
export function searchEmoji(
	query: string,
	groups: readonly EmojiGroup[] = EMOJI_GROUPS,
): EmojiEntry[] {
	const q = fold(query.trim());
	if (!q) return [];
	const words = q.split(/\s+/);
	return groups.flatMap((g) =>
		g.entries.filter((x) => words.every((w) => fold(x.keys).includes(w))),
	);
}
